<a href="https://colab.research.google.com/github/nabillarmdhn/praktikum_Orbit-Guru-Gen-Y/blob/main/Materi%20Experiment_Numpy_Library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Library in Python

A. Cara memanggil numpy untuk pertama kali adalah seperti yang ada di bawah ini

In [ ]:
import numpy as np # Ini adalah cara untuk mengawali ketika memanggil numpy

# Contoh Membuat Array
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float) # "float" adalah sebua perintah untuk menetapkan angka tetap sama(agar bilangan desimal didak dibulatkan)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)
# Misalnya "b = np.array([(1.5,2,3), (4,5,6)], dtype = int" Maka nilai "1.5" akan menjadi 1

In [ ]:
# Menampilkan Array a
a

array([1, 2, 3])

In [ ]:
# Menampilkan Array b
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
# Menampilkan Array c
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

### Initial Placeholders

In [ ]:
# Create an array of zeros
# Nilai identitas matrix adalah (0 dan 1) zeros berguna untuk mencontohkan cara membuat matrix
# Misal (3,6,4) menunjukan bahwa
# (3) menunjukan bahwa ada 3 matrix yang akan di bentuk
# (6) menunjukan bahwa jumlah baris matrix nya ada 6
# (4) menunjukan bahwa  jumlah kolom dalam matrix ada 4
np.zeros((3,6,4,))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
# Create an array of ones
# Adalah contoh matrix identitas 1
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
# Create an array of evenly spaced values (step value)
# Numpy arange
# (5) menunjukan bahwa sebuah urutan bilangan yang di awali dengan angka 5
# (25) dan di akhiri dengan angka
# (4) mrnunjukan bahwa lompatan nya sebanyak 4 angka
d = np.arange(5,25,4)
d

array([ 5,  9, 13, 17, 21])

In [ ]:
# Create an array of evenly spaced values (number of samples)
# Menunjukan macam bilangan apa saja dar1 0-2 dengan jumlah bilangannya 9 angka
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
# Create a constant array
# Perintah untuk membuatkan matrix dengan ordo 2x2(2 baris dan 2 kolom) dengan angka di dalmnya adalah 7
e = np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

In [ ]:
# Create a 2X2 identity matrix (membuat matrix dengan identitas matrix 1 dan 0)
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [ ]:
# Create an array with random values
np.random.random((2,2))

array([[0.75180718, 0.67209764],
       [0.18030929, 0.37617252]])

In [ ]:
# Create an empty array
# Membuat matrix 3 baris dan 2 kolom namun mengubah nilainya menjadi 0
np.empty((3,2))

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

# Contoh Input Output

In [ ]:
# np.save('my_array', a)
# np.savez('array.npz', a, b)
# np.load('my_array.npy')

In [ ]:
# np.loadtxt("myfile.txt")
# np.genfromtxt("my_file.csv", delimiter=',')
# np.savetxt("myarray.txt", a, delimiter=" ")

# Data Types

In [ ]:
# Signed 64-bit integer types
np.int64

In [ ]:
# Standard double-precision floating point
np.float32

numpy.float32

In [ ]:
# Complex numbers represented by 128 floats
np.complex

complex

In [ ]:
# Boolean type storing TRUE and FALSE values
np.bool

In [ ]:
# Python object type
np.object

In [ ]:
# Fixed-length string type
np.string_

In [ ]:
# Fixed-length unicode type
np.unicode_

# Inspecting Your Array 

In [ ]:
# Array dimensions
a.shape

In [ ]:
# Length of array
len(a)

In [ ]:
# Number of array dimensions
b.ndim

In [ ]:
# Number of array elements
e.size

In [ ]:
# Data type of array elements
b.dtype

In [ ]:
# Name of data type
b.dtype.name

In [ ]:
# Convert an array to a different type
b.astype(int)

# Array Mathematics
## Arithmetic Operations

### Subtraction

In [ ]:
# Pengurangan Array - a-b
g = a - b
g

In [ ]:
# Pengurangan Array - a-b
np.subtract(a,b)

In [ ]:
# Penjumlahan Array - b+a
b + a

In [ ]:
# Penjumlahan Array - b+a
np.add(b,a)

### Division

In [ ]:
# Pembagian Array - a/b
a / b

In [ ]:
# Pembagian Array - a/b
np.divide(a,b)

### Multiplication

In [ ]:
# Perkalian Array - a*b
a * b

In [ ]:
# Perkalian Array - a*b
np.multiply(a,b)

### Exponentiation

In [ ]:
# Fungsi eksponensial pada array b
np.exp(b)

### Square root

In [ ]:
# Fungsi akar pada array b
np.sqrt(b)

### Print sines of an array

In [ ]:
# Nilai Sinus pada array a
np.sin(a)

### Element-wise cosine 

In [ ]:
# Nilai Cosinus pada array b
np.cos(b)

### Element-wise natural logarithm

In [ ]:
# Nilai logaritma pada array a
np.log(a)

### Dot product

In [ ]:
# Perkalian Titik pada array f
e.dot(f)


## Comparison

### Element-wise comparison

In [ ]:
# Perbandingan elemen array a==b 
a == b

In [ ]:
# Perbandingan elemen array a<2
a < 2

### Array-wise comparison

In [ ]:
# Perbandingan array a,b
np.array_equal(a, b)

## Aggregate Functions

### Array-wise sum

In [ ]:
# Agregasi nilai total array a
a.sum()

### Array-wise minimum value

In [ ]:
# Agregasi nilai minimal array a
a.min()

### Maximum value of an array row

In [ ]:
# Agregasi nilai maksimal array b
b.max(axis=0)

### Cumulative sum of the elements

In [ ]:
# Nilai kumulatif pada array b
b.cumsum(axis=1)

### Mean

In [ ]:
# Nilai Mean array a
a.mean()

### Median 

In [ ]:
# Nilai Median array b
np.median(b)

### Correlation coefficient

In [ ]:
# Nilai korelasi koefisien array a
np.corrcoef(a)

### Standard deviation

In [ ]:
# Nilai standar defiasi array b
np.std(b)

# Copying Arrays

### Create a view of the array with the same data

In [ ]:
# Melihat isi array a
h = a.view()
h

### Create a copy of the array

In [ ]:
# Copy array a
np.copy(a)

### Create a deep copy of the array

In [ ]:
# Deef copy array a
h = a.copy()
h

# Sorting Arrays

### Sort an array

In [ ]:
# Mengurutkan array a
a.sort()
a

### Sort the elements of an array's axis

In [ ]:
# Mengurutkan array c
c.sort(axis=0)
c

# Subsetting, Slicing, Indexing

## Subsetting

### Select the element at the 2nd index

In [ ]:
# Mengambil nilai index ke 2 pada elemen array a
a[2]

### Select the element at row 1 column 2 (equivalent to b[1][2])


In [ ]:
# Mengambil nilai baris ke 1 kolom ke 2 pada elemen array a
b[1,2]

## Slicing

### Select items at index 0 and 1

In [ ]:
# Mengambil nilai index ke 0 - 1 pada elemen array a
a[0:2]

### Select items at rows 0 and 1 in column 1

In [ ]:
# Mengambil nilai index ke 0 - 1 kolom ke 1 pada elemen array b
b[0:2,1] 

### Select all items at row 0 (equivalent to b[0:1, :])

In [ ]:
# Mengambil semua nilai baris ke 0 pada elemen array b
b[:1]

### Same as [1,:,:]

In [ ]:
# Mengambil semua nilai baris ke 1 pada elemen array c
c[1,...]

### Reversed array a 

In [ ]:
# Mengambil nilai pada elemen array a secara terbalik
a[ : :-1]

# Array Manipulation

## Transposing Array

### Permute array dimensions

In [ ]:
# Transpose array b
i = np.transpose(b)

In [ ]:
i.T

##  Changing Array Shape

### Flatten the array

In [ ]:
b

In [ ]:
# Meratakan array b menjadi satu dimensi
b.ravel()

### Reshape, but don’t change data

In [ ]:
g

In [ ]:
# Mengubah array g menjadi 2 dimensi
g.reshape(3,-2)

## Adding/Removing Elements

### Return a new array with shape (2,6) 

In [ ]:
h

In [ ]:
# Menambah jumlah elemen array
np.resize(h, (2,6))

### Append items to an array

In [ ]:
h

In [ ]:
g

In [ ]:
# Menambahkan elemen array h dengan array g 
np.append(h,g)

### Insert items in an array

In [ ]:
a

In [ ]:
# Memasukkan nilai 5 index ke 1 dalam array a
np.insert(a, 1, 5)

### Delete items from an array

In [ ]:
a

In [ ]:
# Menghapus elemen array a index ke 1
np.delete(a,[1])

## Combining Arrays

###  Concatenate arrays

In [ ]:
a

In [ ]:
d

In [ ]:
# Menggabungkan elemen array a dan d
np.concatenate((a,d),axis=0) 

### Stack arrays vertically (row-wise)

In [ ]:
a

In [ ]:
b

In [ ]:
# Susunan array secara vertikal (berdasarkan baris) array a dan b
np.vstack((a,b))

### Stack arrays vertically (row-wise)

In [ ]:
e

In [ ]:
f

In [ ]:
# Susunan array secara vertikal (berdasarkan baris) array e dan f
np.r_[e,f]

### Stack arrays horizontally (column-wise)

In [ ]:
# Susunan array secara horizontal (berdasarkan kolom) array e dan f
np.hstack((e,f))

### Create stacked column-wise arrays 

In [ ]:
a

In [ ]:
d

In [ ]:
# Susunan berdasarkan kolom array a dan d
np.column_stack((a,d))

### Create stacked column-wise arrays

In [ ]:
# Susunan berdasarkan kolom array a dan d
np.c_[a,d]

## Splitting Arrays

### Split the array horizontally at the 3rd index

In [ ]:
# Memisahkan array a secara horizontal pada indeks ke-3
np.hsplit(a,3)

### Split the array vertically at the 2nd index

In [ ]:
# Memisahkan array c secara vertikal pada indeks ke-2
np.vsplit(c,2)